[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts =
    --screenshot=only-on-failure
    --output=screenshots
    --html=reports/report.html
    --self-contained-html
